### ISSUE TITLE
Checklist of what should be done to productionise

### ISSUE THREAD

**Issue by ensonic** [kubernetes-csi/csi-driver-image-populator#24]
The README mentions that it should not be used it production. What about a checklist of things you consider missing?

**Comment by kfox1111** [comment]
This driver uses skopeo under the hood. It works, but doesn't interact with the chosen container runtime at all. One issue this can lead to is out of disk space. It would be really good I think to rework it to use cri so that the image is integrated with the rest of the container runtime. Last I looked, there wasn't enough functionality in the cri though to fully support it. That may have changed.

**Comment by Elegant996** [comment]
What enhancements to cri were needed? Looking at cri now, the only recent additions were `GetContainerEvents` which may help to know when the image is created and could be mounted.

**Comment by kfox1111** [comment]
Last I talked with the maintainers (years ago) there wasnt a way to build an instance without executing it. There may be a way these days. Also been years since I've looked.

**Comment by ensonic** [comment]
FYI: would it somehow make sense to merge with https://github.com/warm-metal/csi-driver-image. I've now been playing with that one and it works nicely.

**Comment by kfox1111** [comment]
See https://github.com/warm-metal/csi-driver-image/issues/12
